languageCode = "en"
languageName = "English"
weight = 1
title = "Xexhausted"

[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
#  logo = "img/logo.png"
  description = "I'm Xexhausted, an enthusiast in cybersecurity who loves to research things and exploring."
  # copyright = "Copy, _right?_ :thinking_face:"
  dateFormat = "2 January 2006"

[params.author]
  name = "Xexhausted"
  image = "img/avatar.png"
  headline = "Diving deep into research to unravel new possibilities"
  bio = "The only limits you have are the limits you believe.."
   links = [
     { discord = "https://discord.com/users/1106949233237573712" },
     { github = "https://github.com/Xexhausted" },
     { linkedin = "https://www.linkedin.com/in/sahan-shrestha-ba83a6279/" },
     { email = "mailto:xexhausted@ncateam.xyz" },  
 ]
